title: "Sector Universe"
description: "A databank consisting of everything you need to know about the Sector Universe."
theme: minima
minima:
  skin: dark
lang: en

exclude: ["README.md"]

collections:
  pages:
    output: true
    permalink: /:collection/path/