title: "Sector Universe"
description: "A databank consisting of everything you need to know about the Sector Universe."

plugins:
  - jekyll-category-pages

theme: minima
markdown: kramdown
minima:
  skin: dark
lang: en

exclude: ["README.md"]

collections:
  articles:
    output: true
    permalink: /:collection/:path/
  meta:
    output: true
    permalink: /:collection/:path/
    