title: "Sector Universe"
description: "A databank consisting of everything you need to know about the Sector Universe."
theme: minima
minima:
  skin: dark
lang: en

exclude: ["README.md"]

collections:
  sectors:
    output: true
    permalink: /:collection/path/
  species:
    output: true
    permalink: /:collection/path/
  technology:
    output: true
    permalink: /:collection/
  factions:
    output: true
    permalink: /:collection/path/
  events:
    output: true
    permalink: /:collection/path/
  culture:
    output: true
    permalink: /:collection/path/
  meta:
    output: true
    permalink: /:collection/:path/