name: Index markdown files

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
        
      - name: install packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: execute script
        run: |
          python file-index.py
      
      - name: deploy
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          git pull origin master
          git add -f meta/page_index.md
          git commit -m "index all files"
          git push origin master
